### ISSUE TITLE
başlıkların görünümündeki sorun

### ISSUE THREAD

**Issue by mitsukisourtimes** [ssg/eksi-yedek#1]
başlıklar mobil görünümünde iki satıra ulaştığında alt alta dizilmek yerine birbirlerinin üstüne kadar giriyor. ekranın dikey kullanımında bu şekilde: 

![Screenshot_20240813_100744_Chrome](https://github.com/user-attachments/assets/61c27a55-ff50-4543-80bd-812ecc972c2b)

kullandığım cihaz: samsung galaxy a13, android 14, one ui 6.1
tarayıcı: twitter'ın kendi tarayıcısı ama chrome destekli sanırım. (edit: tahmin ettiğim gibi, google chrome'da da denedim ve aynı.)

**Comment by onurravli** [comment]
#2 ile cozulmus olmasi gerekiyor. ping @ssg

**Comment by mitsukisourtimes** [comment]
> #2 ile cozulmus olmasi gerekiyor. ping @ssg

maalesef çözülmedi. aynı sorun bende devam ediyor.

**Comment by onurravli** [comment]
> > #2 ile cozulmus olmasi gerekiyor. ping @ssg
> 
> maalesef çözülmedi. aynı sorun bende devam ediyor.

daha merge'lenmedi, benim forku mu denediniz?

**Comment by ssg** [comment]
@onurravli sende bu halinin calisir bir kopyasi var mi, nasil gorundugune bakayim. line-height kaldirinca content ve baslik arasi cok aciliyordu son baktigimda cunku. yamulmasin.
