### ISSUE TITLE
asterisk bkz'lar görünmüyor.

### ISSUE THREAD

**Issue by mitsukisourtimes** [ssg/eksi-yedek#4]
yedek okumada entry'lerdeki asterisk bkz'lar görüntülenmiyor, bu bkz'ların yazıldığı kısımda satır atlatıyor.

cihaz bilgileri: samsung galaxy a135f, android 14, one ui 6.1
tarayıcı bilgileri: google chrome, sürüm 129.0.6668.100

görseller:

![Screenshot_20241016_004240_eki szlk](https://github.com/user-attachments/assets/59a97d4e-a711-4974-8159-8cf06bfa41ba)
![20241016_004141](https://github.com/user-attachments/assets/2615c65c-8373-4e0d-88f7-f5cb00a4a0e8)

**Comment by ssg** [comment]
fixed! tesekkurler @mitsukisourtimes :)

**Comment by skacurt** [comment]
Bu issue'da taraf değilim, commit de bana ait değil, ben nasıl araya kaynamışım 😁 bilinen bir bug mı, rapor edilmeli mi @ssg ?

![Image](https://github.com/user-attachments/assets/dcc29e5d-e3a4-4c6c-ad66-b9f20f696f2f)

**Comment by ssg** [comment]
@skacurt herhalde bug. bahsettiği commit'in #5 'teki commit galiba ama bununla karışmış bi şekilde. bence github buna raporlasak da bakmaz. büyük bi proje olsaydı belki.
